# Generated by Django 4.2.6 on 2023-11-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='apple',
        ),
    ]
