# Generated by Django 3.0.6 on 2024-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitapp', '0002_rename_place_apple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
